// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RESTORE.Data;

#nullable disable

namespace RESTORE.Migrations
{
    [DbContext(typeof(ReStoreDbContext))]
    [Migration("20240401112714_UploadProductImage")]
    partial class UploadProductImage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.2.24128.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RESTORE.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bff50538-cb79-4a3c-8634-1d794cc5b484"),
                            Brand = "Brand",
                            Description = "Description 1",
                            Name = "Product 1",
                            PictureUrl = "url_to_image_1.jpg",
                            Price = 100L,
                            QuantityInStock = 10,
                            Type = "Type"
                        },
                        new
                        {
                            Id = new Guid("cc050597-3aed-4b98-83d3-51acfb895e10"),
                            Brand = "Brand",
                            Description = "Description 2",
                            Name = "Product 2",
                            PictureUrl = "url_to_image_2.jpg",
                            Price = 200L,
                            QuantityInStock = 20,
                            Type = "Type"
                        },
                        new
                        {
                            Id = new Guid("35808198-b71d-417e-8292-2070d8bcf459"),
                            Brand = "Brand",
                            Description = "Description 3",
                            Name = "Product 3",
                            PictureUrl = "url_to_image_3.jpg",
                            Price = 300L,
                            QuantityInStock = 30,
                            Type = "Type"
                        },
                        new
                        {
                            Id = new Guid("5e1ad86d-4c41-45a4-a95a-9ccb224ace60"),
                            Brand = "Brand",
                            Description = "Description 4",
                            Name = "Product 4",
                            PictureUrl = "url_to_image_4.jpg",
                            Price = 400L,
                            QuantityInStock = 40,
                            Type = "Type"
                        },
                        new
                        {
                            Id = new Guid("6e685262-b634-49e6-8046-0cc9804a76a3"),
                            Brand = "Brand",
                            Description = "Description 5",
                            Name = "Product 5",
                            PictureUrl = "url_to_image_5.jpg",
                            Price = 500L,
                            QuantityInStock = 50,
                            Type = "Type"
                        },
                        new
                        {
                            Id = new Guid("c9a76fa7-11a9-4ee9-8252-f8f10bc85840"),
                            Brand = "Brand",
                            Description = "Description 6",
                            Name = "Product 6",
                            PictureUrl = "url_to_image_6.jpg",
                            Price = 600L,
                            QuantityInStock = 60,
                            Type = "Type"
                        },
                        new
                        {
                            Id = new Guid("3e91e3db-63a3-41f7-81e2-17dc7041f92e"),
                            Brand = "Brand",
                            Description = "Description 7",
                            Name = "Product 7",
                            PictureUrl = "url_to_image_7.jpg",
                            Price = 700L,
                            QuantityInStock = 70,
                            Type = "Type"
                        },
                        new
                        {
                            Id = new Guid("88dc563d-2087-4d56-bbde-1eb603d39e58"),
                            Brand = "Brand",
                            Description = "Description 8",
                            Name = "Product 8",
                            PictureUrl = "url_to_image_8.jpg",
                            Price = 800L,
                            QuantityInStock = 80,
                            Type = "Type"
                        },
                        new
                        {
                            Id = new Guid("28312368-7d6f-49cc-8f5c-40c0f0f60d74"),
                            Brand = "Brand",
                            Description = "Description 9",
                            Name = "Product 9",
                            PictureUrl = "url_to_image_9.jpg",
                            Price = 900L,
                            QuantityInStock = 90,
                            Type = "Type"
                        },
                        new
                        {
                            Id = new Guid("511c12a7-6f39-4e24-bc62-450d77cfac03"),
                            Brand = "Brand",
                            Description = "Description 10",
                            Name = "Product 10",
                            PictureUrl = "url_to_image_10.jpg",
                            Price = 1000L,
                            QuantityInStock = 100,
                            Type = "Type"
                        });
                });

            modelBuilder.Entity("RESTORE.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
